#ask the user to guess how long he/she needs to wait for random seconds generated by system

import random
import datetime

def compare_seconds(target, elapsed):
    difference = elapsed - target
    
    if difference > 0:
        print(f"{difference} seconds .. too slow")
    elif difference < 0:
        print(f"{difference * -1} seconds .. too quick")
    else:
        print(f"Great Job. right on time !")


if __name__ == "__main__":

    target = random.randint(2,6)
    print(f"Your target time is {target} seconds.")
    print(f"--- How to play - Press Enter to Begin and press Enter again after {target} seconds. --- \n")

    input("--- Press Enter to Begin ---")
    start_time = datetime.datetime.now()

    input("--- Press Enter again to End ---")
    elapsed = datetime.datetime.now() - start_time
    
    print("Elapsed Time: ", elapsed)
    compare_seconds(target, elapsed.seconds)
   
        
            
